### ISSUE TITLE
macOS <= 10.8 (only Intel with clang) fails with: error: unknown type name 'dispatch_semaphore_t'

### ISSUE THREAD

**Issue by barracuda156** [AcademySoftwareFoundation/openexr#1449]
This is `openexr` 3.1.8.
Something does not work right still with eary macOS on Intel with Clang:

```
[ 19%] Building CXX object src/lib/IlmThread/CMakeFiles/IlmThread.dir/IlmThreadSemaphoreWin32.cpp.o
cd /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/build/src/lib/IlmThread && /opt/local/bin/clang++-mp-16 -DILMTHREAD_EXPORTS -DIlmThread_EXPORTS -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/build/src/lib/IlmThread -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/openexr-3.1.8/src/lib/IlmThread -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/build/cmake -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/openexr-3.1.8/src/lib/Iex -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -arch x86_64 -mmacosx-version-min=10.8 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT src/lib/IlmThread/CMakeFiles/IlmThread.dir/IlmThreadSemaphoreWin32.cpp.o -MF CMakeFiles/IlmThread.dir/IlmThreadSemaphoreWin32.cpp.o.d -o CMakeFiles/IlmThread.dir/IlmThreadSemaphoreWin32.cpp.o -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/openexr-3.1.8/src/lib/IlmThread/IlmThreadSemaphoreWin32.cpp
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/openexr-3.1.8/src/lib/IlmThread/IlmThreadSemaphorePosixCompat.cpp:25:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_graphics_openexr/openexr/work/openexr-3.1.8/src/lib/IlmThread/IlmThreadSemaphore.h:64:13: error: unknown type name 'dispatch_semaphore_t'
    mutable dispatch_semaphore_t _semaphore;
            ^
1 error generated.
```
Log from 10.8.5: https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/136984/steps/install-port/logs/stdio

Everything from 10.9 up builds fine with Clangs on Intel, and 10.6 builds fine with GCC for PowerPC (we did not test GCC with other macOS versions).

**Comment by meshula** [comment]
It's available as of 10.6 (https://developer.apple.com/documentation/dispatch/dispatch_semaphore_t?language=objc) so it must be a missing #include? Sorry I don't know which one.

**Comment by barracuda156** [comment]
@meshula Ha, maybe that was fixed already by https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b but 3.1.8 did not include that commit for some reason (?).

**Comment by meshula** [comment]
@cary-ilm Did we miss this one, or do we need to dig a bit more to discover the problem?

**Comment by barracuda156** [comment]
@meshula As I recall, it was added specifically to address either this issue or something very similar. Those version macros should not be used with underscore prefix, since some early systems fail to understand them (if Clang, then that commit should fix the present ticket issue, I think).

**Comment by meshula** [comment]
Yes, I recall that discussion, thanks for the reminder.

**Comment by barracuda156** [comment]
(At worst, https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b commit may not fix the issue, but it won’t hurt in any case.)

**Comment by barracuda156** [comment]
@meshula Judging by 10.6 x86 (which was broken earlier), my fix from https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b works as intended: https://ports.macports.org/port/openexr/details (10.7–10.8 status is old, buildbots are lagging).

**Comment by meshula** [comment]
Great! So are you good for now, or are you requesting a patch of https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b into 3.1.8?

**Comment by barracuda156** [comment]
> Great! So are you good for now, or are you requesting a patch of [6773e77](https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b) into 3.1.8?

@meshula Please include https://github.com/AcademySoftwareFoundation/openexr/commit/6773e77bade3b4d8284881e477bee9c1f91c0f8b in the next release. (Until then we can keep our local patch.)

**Comment by cary-ilm** [comment]
This should be addressed in v3.1.9. Feel free to reopen if anything is amiss.

**Comment by barracuda156** [comment]
Great, then patches in Macports can be dropped. I will test this today.
