### ISSUE TITLE
Build broke with commit 7592a57

### ISSUE THREAD

**Issue by tellypresence** [AcademySoftwareFoundation/openexr#2629]
[`7592a57`](https://github.com/AcademySoftwareFoundation/openexr/commit/7592a57e79d7e428b5e0a1bf67d1f9be3f887ea3) broke build:

`#include "openexr_attr.h"` added to `src/lib/OpenEXR/ImfCompression.h`

Build fails with error e.g.
```
.../src/lib/OpenEXR/ImfCompression.h:21:10: fatal error: 'openexr_attr.h' file not found
```

(Note: file `src/lib/OpenEXRCore/openexr_attr.h` exists, but the bare filename `#include` fails to pick it up)

**Comment by cary-ilm** [comment]
I'm not seeing this error. Has this been resolved? If not, can you explain more about the context that triggers it?

**Comment by tellypresence** [comment]
I just tried with latest [`ae697da`](https://github.com/AcademySoftwareFoundation/openexr/commit/ae697da079be370916f2e2fca18220664bc62509) and it built OK, no longer a problem
