### ISSUE TITLE
imath caching issue

### ISSUE THREAD

**Issue by palemieux** [AcademySoftwareFoundation/openexr#2441]
To replicate on Ubuntu:

```
git clone https://github.com/AcademySoftwareFoundation/openexr.git --depth 1
cd openexr
mkdir build
cd build/
cmake ..
make
cmake ..
make
```
results in the error:

```
/home/pal/Downloads/openexr/src/lib/OpenEXRCore/openexr_config.h:12:10: fatal error: Imath/ImathConfig.h: No such file or directory
   12 | #include <Imath/ImathConfig.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
```

The issue seems to be related to:

https://github.com/AcademySoftwareFoundation/openexr/blob/cadf06b7c990e23803df90046464d49fd79d7f58/cmake/OpenEXRSetup.cmake#L438

Removing the caching seems to fix the issue:

```
    target_include_directories(Imath INTERFACE
      "$<BUILD_INTERFACE:${Imath_SOURCE_DIR}/src>")
    if(EXISTS "${_openexr_imath_gen_cfg}")
      target_include_directories(ImathConfig INTERFACE
        "$<BUILD_INTERFACE:${_openexr_imath_cfg_compat}>")
```

**Comment by cary-ilm** [comment]
Looks like this was a regression I introduced in #2376. I've got a patch coming shortly.

**Comment by cary-ilm** [comment]
Addressed in #2443

**Comment by meshula** [comment]
@cary-ilm Can we close this one?
