### ISSUE TITLE
ilmbase 2.3.0 fails to build in FreeBSD 11.2

### ISSUE THREAD

**Issue by mandree** [AcademySoftwareFoundation/openexr#338]
Greetings,

I was trying to upgrade the ilmbase and OpenEXR ports in FreeBSD to v2.3.0 - but it appears that there are too many Linux/i386 issues such that I consider the effort unviable. It looks like we need to skip v2.3.0 on FreeBSD and stick to v2.2.1, which is unfortunate.

With ilmbase, I find that:
 * the cmake build is now totally broken (no matter if using ninja or make) because most variables aren't defined, and I need to set on the command line several variables listed in https://github.com/openexr/openexr/blob/master/README.md#building-with-cmake - these would not appear in ccmake. 
 * "SOVERSION" appears verbatim in the file names (this is with FreeBSD 11.2 and cmake 3.11.2), rather than 24.
 * under cmake, no libraries are built unless I define, among others, -DOPENEXR_BUILD_STATIC=bool:true
 * the GNU configure script is bash-specific and does not work with a plain POSIX /bin/sh and fails.

So, if I use the GNU configure stuff and use bash for the configure shell, I can get past these issues at least, and now for the real regressions in the code:

 * ilmbase 2.3.0 now uses many Linux-specific or obsolete sigaction() features, FreeBSD does not have asm/sigcontext.h, so we get several errors from IexMathFpu.cpp around _fpstate and fpregs, and sa_restorer isn't exposed in FreeBSD (but ilmbase tampers with it - Linux's manpage clearly states "Not intended for application use"). I can't seem to find the required FPE struct elements with "grep -r SOMEFEATURE /usr/include" on FreeBSD. This appears to be a major regression since v2.2.1.
 * ilmbase 2.3.0 uses SA_NOMASK, which isn't defined on FreeBSD (SA_NODEFER is, however).
 * I haven't gotten around to try to build OpenEXR 2.3.0, it doesn't work with ilmbase v2.2.1 (which doesn't surprise me though).

We have always needed some local patches to get OpenEXR to compile on FreeBSD, but with 2.3.0, I am at a loss about IexMathFpu.*.

**Comment by kdt3rd** [comment]
Yes, sorry, we inadvertently broke the cmake build when making the separate packages for ilmbase and openexr in making the 2.3.0 release. It isn't ideal, but until we get a new patch out, you should be able to use cmake if you clone the tag in the repository and compile all the libraries at once using the top level cmake file.

We had tried to incorporate as many of the ad-hoc patches to get the various OS variants compiling, sorry to hear that we made FreeBSD worse, we probably inverted some checks for windows that then enabled the linux path for FreeBSD.

I do not currently have access to a FreeBSD machine to poke around, as the machine I have to fiddle with OS is currently missing a power supply, so could you post the output of "gcc -dM -E - < /dev/null" (or if you use clang, it supports the same)?

for now, could you potentially change the generated config.h (well, IlmBaseConfig.h) to undefine the HAVE_UCONTEXT_H and then report other errors you find in the code? It would be good to get any of those errors fixed so you don't have to maintain a separate set of patches...

**Comment by mandree** [comment]
* The default compiler on FreeBSD 11.2 amd64 is clang 6.0.0, installed as cc. Other versions and/or architectures (ARM64, for instance) may use other defaults.
* The ports collection currently (as of today) defaults to using GCC 7 for gcc, which currently is at 7.3.0.
* The desired predefined macros, fed through "sort -f":
   * [FreeBSD-11.2-amd64-clang.txt](https://github.com/openexr/openexr/files/2364150/FreeBSD-11.2-amd64-clang.txt)
   * [FreeBSD-11.2-amd64-gcc.txt](https://github.com/openexr/openexr/files/2364151/FreeBSD-11.2-amd64-gcc.txt)

**Comment by mandree** [comment]
changing IlmBaseConfig.h to `#undef HAVE_UCONTEXT_H` post-configure helped quite a bit... using that and switching ilmbase to use the GNU autotools/configure based build rig, I can build ilmbase and then OpenEXR as well on FreeBSD 11.2 amd64.

**Comment by KBentley57** [comment]
FWIW, I am facing similar issues to OP on Ubuntu 16.04.  There are more errors than I'm able to find my way around in CMake.  The configure scripts seem like they mostly build, with exception to a missing declaration of expTable and logTable.

**Comment by mandree** [comment]
@KBentley57 build on a fully updated Ubuntu 16.04.5 on amd64 alias x64_64 works for me. Note I do an out-of-path build as follows:

0. `ldconfig` # just in case...
1. `tar xf openexr-2.3.0.tar.gz`
2. `cd openexr-2.3.0`
3. `mkdir -p _build-automake && cd _build-automake`
4. `../configure && make`

**Comment by KBentley57** [comment]
Mandree,

I'll try that out tonight.  However, I wasn't trying to build openexr
byitself, I was trying to build ILMBase separately and then build OpenEXR
afterwards.

**Comment by kdt3rd** [comment]
fyi, we have completely overhauled the cmake build infrastructure, in addition to the checks for ucontext.h, etc. You can test against a clone of current master, or when we make the next release. We have upped the required version of cmake such that we could replace fragile python search scripts, sorry if that causes any issues. Please let us know if the current master works better on freebsd, and thanks for reporting the issues on platforms we don't have - helps make our code better.

**Comment by mandree** [comment]
Thanks. It would seem at first glance that the cmake build for the IlmBase/ directory now works on FreeBSD 12.0-RELEASE amd64. 

Findings as of 21c307aaf054f304f52bb488258f81d68e38385f:

1. OpenEXR per se does not seem to find boost::python although I installed both the py27- and py36- variants. 
1. There is a compilation failure (with the cmake rig for OpenEXR as a whole) in several files, always missing rmdir() declaration, I am showing only one example:
```
[219/299] Building CXX object OpenEXR/IlmImfTest/CMakeFiles/IlmImfTest.dir/main.cpp.o
FAILED: OpenEXR/IlmImfTest/CMakeFiles/IlmImfTest.dir/main.cpp.o 
/usr/local/libexec/ccache/c++  -DILM_IMF_TEST_IMAGEDIR=\"/home/mandree/VCS-other/openexr.git/OpenEXR/IlmImfTest/\" -IOpenEXR/IlmImfTest -I../OpenEXR/IlmImfTest -I../OpenEXR/IlmImf -IOpenEXR/config -I../IlmBase/Iex -IIlmBase/config -I../IlmBase/Half -I../IlmBase/Imath -I../IlmBase/IexMath -I../IlmBase/IlmThread -O3 -DNDEBUG   -pthread -std=gnu++14 -MD -MT OpenEXR/IlmImfTest/CMakeFiles/IlmImfTest.dir/main.cpp.o -MF OpenEXR/IlmImfTest/CMakeFiles/IlmImfTest.dir/main.cpp.o.d -o OpenEXR/IlmImfTest/CMakeFiles/IlmImfTest.dir/main.cpp.o -c ../OpenEXR/IlmImfTest/main.cpp
../OpenEXR/IlmImfTest/main.cpp:217:5: error: use of undeclared identifier 'rmdir'
    rmdir (tempDir.c_str());
    ^
1 error generated.
```
This is caused by a missing or masked `#include <unistd.h>` in these files:
- OpenEXR/IlmImfTest/main.cpp
- OpenEXR/IlmImfTest/testCompositeDeepScanLine.cpp
- OpenEXR/IlmImfUtilTest/main.cpp
- OpenEXR/IlmImfUtilTest/testDeepImage.cpp
- OpenEXR/exrmaketiled/makeTiled.cpp
- OpenEXR/exrmultipart/exrmultipart.cpp

**Comment by kdt3rd** [comment]
I would apologize, for being lazy, but well, I'm lazy and don't have a VM running freebsd. But with recent cleanups, I believe I changed the masking to be what should be such that unistd.h is found more by default. Some of the files you mention not compiling I don't know why, and I don't see any masking, so I suspect a missing include (or something that was accidentally fixed). But if I could impose to ask you to test with the latest master, build and post a log of the failures, I'd like to fix any spots I missed (i.e. perhaps a ninja -k 100 or similar so we see more than just the first) such that freebsd works out of the gate for the main libraries... We are getting inches away from another official release branch, so thanks in advance!

As for the python failures, that one is probably due to boost::python being inconsistent about their config naming... /sigh We have a plan to replace boost::python usage w/ pybind11 in the next version, but until then, let's get the main stuff working first, then we'll worry about python - we have similar issues on other O.S. we are trying to discover we hadn't handled, so maybe during that final cleanup, we'll get the pattern correct for the bsd installs...

**Comment by mandree** [comment]
> I would apologize, for being lazy, but well, I'm lazy and don't have a VM running freebsd. But with recent cleanups, I believe I changed the masking to be what should be such that unistd.h is found more by default. Some of the files you mention not compiling I don't know why, and I don't see any masking, so I suspect a missing include (or something that was accidentally fixed). But if I could impose to ask you to test with the latest master, build and post a log of the failures, I'd like to fix any spots I missed (i.e. perhaps a ninja -k 100 or similar so we see more than just the first) such that freebsd works out of the gate for the main libraries... We are getting inches away from another official release branch, so thanks in advance!

Kimball, 36fb144da1110232bf416d5e1c4abde263056d17 looks better on FreeBSD, it only fails around "cannot find boost/python.hpp" which I don't understand as I have the file, but note it is in /usr/local/include and FreeBSD compilers do NOT look there by default, you DO NEED an -I/usr/local/include, and a corresponding -L/usr/local/lib for the linker.

> As for the python failures, that one is probably due to boost::python being inconsistent about their config naming... /sigh We have a plan to replace boost::python usage w/ pybind11 in the next version, but until then, let's get the main stuff working first, then we'll worry about python - we have similar issues on other O.S. we are trying to discover we hadn't handled, so maybe during that final cleanup, we'll get the pattern correct for the bsd installs... 

boost::python failures see here:
[build2.log](https://github.com/openexr/openexr/files/3510412/build2.log)

Thanks and hope that helps. Let me know if you need more.

**Comment by kdt3rd** [comment]
It should be that the find_package(boost) would have included those header paths if they are non-compiler standard. Perhaps that is a weakness in cmake that it assumes /usr/local/include is in the system path? I know that it will remove duplicate paths from the include path prior to emitting compile commands, and if it thinks it's in the default system include path, it skips adding the include.

But I am relying on the includes / library paths be set by the imported Boost::python27/37 library and not specifying them manually. In /usr/share/cmake-X.XX/Modules/FindBoost.cmake, there should be a foreach(COMPONENT) loop at around line 2210 (that's where it is in 3.15.1 anyway), and during that it should be setting the include dirs and libraries for all the boost components. Then we just say something like target_link_libraries(xxxxx Boost::python27), although we allow multiple python versions, so it is a bit more convoluted.

If you could look at your build/CMakeCache.txt file, it should have a Boost_INCLUDE_DIR and that should be /usr/local/include, and then if you are compiling with ninja, the LINK_LIBRARIES for libPyImath_Python2_7, should have the full path to boost_python, i.e. something like /usr/local/lib/libboost_python27.so. If not, you can try setting -DBOOST_ROOT=/usr/local when you run cmake.

If those components are there, then it seems like it should just work. As a work around, you can do something like:

```
mkdir build
cd build
env CXXFLAGS="-I/usr/local/include" cmake -G Ninja -DBOOST_ROOT=/usr/local ..
ninja -v
```
and see if that works (and links against boost_python appropriately), and you see the -I/usr/local/include in there...

Oh, and what version of boost are you compiling against (I'm still on 1.69)? I know in 1.70, they changed something about the headers library, although I thought that was for header-only libs, so shouldn't affect the python stuff, but is a possibility. If you are on 1.70, then maybe try adding headers to the list of optional components to find (line 74 of PyIlmBase/CMakeLists.txt), and then at line 96 of PyIlmBase/config/ModuleDefine.cmake, add Boost::headers to the end of the list APPEND call there. If *that* works, then let me know, and I can add the necessary fallback checks and all that, but we would have isolated where the header path is coming from.

I am not 100% sure how to debug past there yet as to why /usr/local/include wouldn't appear in the include path, but hopefully one of the above will expose why it's not working and we can go from there.

**Comment by mandree** [comment]
I have Boost 1.70, and it appears the minimum survival is:
```
env CXXFLAGS="-I/usr/local/include" cmake -G Ninja ..
```

Without the `CXXFLAGS` set in the environment, that `-I/usr/local/include` remains missing from the compiler invocations. I am picking a random of the dozen failures, look (and ccache uses "FreeBSD clang version 6.0.1" from /usr/bin, i. e. the system default compiler on 12.0-RELEASE x86_64 = amd64):

```
$ ninja -v -j1
[1/73] /usr/local/libexec/ccache/c++  -Diex_python3_EXPORTS -IPyIlmBase/PyIex -I../PyIlmBase/PyIex -I../IlmBase/Iex -IIlmBase/config -I../IlmBase/IexMath -isystem /usr/local/include/python3.6m -O3 -DNDEBUG -fPIC -MD -MT PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o -MF PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o.d -o PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o -c ../PyIlmBase/PyIex/iexmodule.cpp
FAILED: PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o 
/usr/local/libexec/ccache/c++  -Diex_python3_EXPORTS -IPyIlmBase/PyIex -I../PyIlmBase/PyIex -I../IlmBase/Iex -IIlmBase/config -I../IlmBase/IexMath -isystem /usr/local/include/python3.6m -O3 -DNDEBUG -fPIC -MD -MT PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o -MF PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o.d -o PyIlmBase/PyIex/CMakeFiles/iex_python3.dir/iexmodule.cpp.o -c ../PyIlmBase/PyIex/iexmodule.cpp
../PyIlmBase/PyIex/iexmodule.cpp:36:10: fatal error: 'boost/python.hpp' file not found
#include <boost/python.hpp>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

The thing seems to be, that clang does **not** look into /usr/local/include (same if I use LLVM 8 from FreeBSD's ports), while GCC 9.2 **does**. Not sure if `-isystem` plays its role here.

Running cmake without or with `CXXFLAGS=-I/usr/local/include`, I see these warnings in cmake output:
```
[...]
-- Configure PyIlmBase Version: 2.3.0 Lib API: 24.0.2
-- Found Python: /usr/local/bin/python3.6 (found version "3.6.9") found components:  Interpreter Development 
-- Found Python2: /usr/local/bin/python2.7 (found version "2.7.16") found components:  Interpreter Development 
-- Found Python3: /usr/local/bin/python3.6 (found version "3.6.9") found components:  Interpreter Development 
: Found Python 2.7.16 and 3.6.9
-- Found Python2 libraries: 27
-- Found Python3 libraries: 36
-- Found Boost: /usr/local/include (found version "1.70.0") found components:  python27 python36 missing components:  python python2 python3
Found Python 2 boost: Boost::python27
Found Python 3 boost: Boost::python36
CMake Warning at PyIlmBase/config/NumPyLocate.cmake:40 (message):
  Found numpy version in python 2.7.16, but unable to locate header files
Call Stack (most recent call first):
  PyIlmBase/CMakeLists.txt:133 (include)


CMake Warning at PyIlmBase/config/NumPyLocate.cmake:82 (message):
  Found numpy version in python 3.6.9, but unable to locate header files
Call Stack (most recent call first):
  PyIlmBase/CMakeLists.txt:133 (include)


-- Configure OpenEXR Viewers Version: 2.3.0 Lib API: 24.0.1
[...]
```

In CMakeCache.txt without that option:

```
//Path to a file.
Boost_INCLUDE_DIR:PATH=/usr/local/include

//Boost library directory DEBUG
Boost_LIBRARY_DIR_DEBUG:PATH=/usr/local/lib

//Boost library directory RELEASE
Boost_LIBRARY_DIR_RELEASE:PATH=/usr/local/lib

//Disable the search for boost-cmake
Boost_NO_BOOST_CMAKE:BOOL=ON
```

and it does find libboost_python27.so for `Boost_PYTHON27_LIBRARY_DEBUG` and `Boost_PYTHON36_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_python36.so` (same for _RELEASE).

What does **not** seem to help, is adding Boost::headers like so:

```
diff --git a/PyIlmBase/config/ModuleDefine.cmake b/PyIlmBase/config/ModuleDefine.cmake
index f983683..2d230df 100644
--- a/PyIlmBase/config/ModuleDefine.cmake
+++ b/PyIlmBase/config/ModuleDefine.cmake
@@ -93,7 +93,7 @@ function(PYILMBASE_DEFINE_MODULE modname)
   endif()
   # NB: make this one last so we can cheat and add the python and boost
   # libs as private deps at the end regardless of whether it was provided
-  list(APPEND libarglist PRIVATE_DEPS ${PYILMBASE_CURMOD_PRIVATE_DEPS})
+  list(APPEND libarglist PRIVATE_DEPS ${PYILMBASE_CURMOD_PRIVATE_DEPS} Boost::headers)
   if(TARGET Python2::Python AND TARGET Boost::${PYILMBASE_BOOST_PY2_COMPONENT})
     set(libname "${PYILMBASE_CURMOD_LIBNAME}${PYILMBASE_LIB_PYTHONVER_ROOT}${Python2_VERSION_MAJOR}_${Python2_VERSION_MINOR}")
     set(extraDeps ${PYILMBASE_CURMOD_MODULE_DEPS})
```

Unfortunately, I am rather ignorant about CMake, so I'm not sure if the above helps or how to go on from here. I have added cmake traces (unexpanded and expanded) and a diff between the variable traces that ignores the irrelevant non-reproducible tempnames. Unfortunately I need to zip-store an .xz again so that github will accept the file (xz -e9 compresses these logs so much better than anything else - <175k vs. 900 k for gzip):
[cmake-traces.tar.xz.zip](https://github.com/openexr/openexr/files/3511958/cmake-traces.tar.xz.zip)

**Comment by kdt3rd** [comment]
Oh, this is at least something. I am kind of glad the new headers stuff isn't the source of issues. I will try to add a force of the boost include path to the cmake builds and we can see if it is still getting stripped. While I look through the log files you posted, could I ask you for the output of the following snippet:

[this should work fine in most shells, works in zsh anyway :)]
```
numpydir=`python3 -c "import numpy; print(numpy.get_include())"`
echo $numpydir
ls -lR $numpydir
unset numpydir
```
The thing that is failing and spitting out warnings once you set the CXXFLAGS is the find of the header file for our antiquated use of the numpy array extension (in our next major version, we will replace this with the native python array buffer bindings, but trying to get things stabilized and cleaned up first).

**Comment by mandree** [comment]
[Boost 1.71 appears to have landed in FreeBSD ports, but I need to postpone upgrading and testing by a day or two.]

Well, turns out that the `Found numpy version in python 3.6.9, but unable to locate header files` was misleading, the package **was not** installed for my attempts above, as your `python3 -c "import numpy..."` clearly showed with an import failure. 

Making up for that, with py36-numpy freshly installed, I now get (note the `-- Found NumPy 1.16.4 for Python 3.6.9: /usr/local/lib/python3.6/site-packages/numpy/core/include`):
```
$ numpydir=`python3 -c "import numpy; print(numpy.get_include())"`
$ echo $numpydir
/usr/local/lib/python3.6/site-packages/numpy/core/include
$ ls -lR $numpydir
total 2
drwxr-xr-x  2 root  wheel  28 20 Aug. 00:25 numpy

/usr/local/lib/python3.6/site-packages/numpy/core/include/numpy:
total 349
-rw-r--r--  1 root  wheel  60958 17 Aug. 03:27 __multiarray_api.h
-rw-r--r--  1 root  wheel  12143 17 Aug. 03:27 __ufunc_api.h
-rw-r--r--  1 root  wheel   1861  4 Feb.  2018 _neighborhood_iterator_imp.h
-rw-r--r--  1 root  wheel   1014 17 Aug. 03:27 _numpyconfig.h
-rw-r--r--  1 root  wheel    164 31 Jan.  2019 arrayobject.h
-rw-r--r--  1 root  wheel   3509 28 Feb.  2018 arrayscalars.h
-rw-r--r--  1 root  wheel   1878 21 Feb. 18:33 halffloat.h
-rw-r--r--  1 root  wheel  56385 17 Aug. 03:27 multiarray_api.txt
-rw-r--r--  1 root  wheel  11507 21 Feb. 18:33 ndarrayobject.h
-rw-r--r--  1 root  wheel  64719 27 Mai  14:41 ndarraytypes.h
-rw-r--r--  1 root  wheel   6786 21 Feb. 18:33 noprefix.h
-rw-r--r--  1 root  wheel   4715 21 Feb. 18:33 npy_1_7_deprecated_api.h
-rw-r--r--  1 root  wheel  14666 21 Feb. 18:33 npy_3kcompat.h
-rw-r--r--  1 root  wheel  37277 27 Mai  14:41 npy_common.h
-rw-r--r--  1 root  wheel   3879 21 Feb. 18:33 npy_cpu.h
-rw-r--r--  1 root  wheel   2596 21 Feb. 18:33 npy_endian.h
-rw-r--r--  1 root  wheel   3439 21 Feb. 18:33 npy_interrupt.h
-rw-r--r--  1 root  wheel  18838 27 Mai  14:41 npy_math.h
-rw-r--r--  1 root  wheel    567 28 Feb.  2018 npy_no_deprecated_api.h
-rw-r--r--  1 root  wheel    817  4 Feb.  2018 npy_os.h
-rw-r--r--  1 root  wheel   1207 21 Feb. 18:33 numpyconfig.h
-rw-r--r--  1 root  wheel   6306 28 Feb.  2018 old_defines.h
-rw-r--r--  1 root  wheel    708 21 Feb. 18:33 oldnumeric.h
-rw-r--r--  1 root  wheel   6889 17 Aug. 03:27 ufunc_api.txt
-rw-r--r--  1 root  wheel  13051 27 Mai  14:41 ufuncobject.h
-rw-r--r--  1 root  wheel    729 21 Feb. 18:33 utils.h
```

And this then changes cmake output a bit:
```
$ CXXFLAGS="-I/usr/local/include" cmake --warn-uninitialized -G Ninja .. 
Warn about uninitialized values.
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/local/libexec/ccache/cc
-- Check for working C compiler: /usr/local/libexec/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configure ILMBASE Version: 2.3.0 Lib API: 24.0.0
-- Setting build type to 'Release' as none was specified.
-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - found
-- Performing Test ILMBASE_HAVE_CONTROL_REGISTER_SUPPORT
-- Performing Test ILMBASE_HAVE_CONTROL_REGISTER_SUPPORT - Failed
-- Looking for include file asm/sigcontext.h
-- Looking for include file asm/sigcontext.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for include file semaphore.h
-- Looking for include file semaphore.h - found
-- Looking for sem_init in pthread
-- Looking for sem_init in pthread - found
-- Configure OpenEXR Version: 2.3.0 Lib API: 24.0.0
CMake Warning (dev) at OpenEXR/config/OpenEXRSetup.cmake:21 (set):
  uninitialized variable 'ILMBASE_VERSION'
Call Stack (most recent call first):
  OpenEXR/CMakeLists.txt:23 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN - Success
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX - Success
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
CMake Warning (dev) at OpenEXR/config/CMakeLists.txt:104 (set):
  uninitialized variable 'CMAKE_THREAD_LIBS_INIT'
Call Stack (most recent call first):
  OpenEXR/config/CMakeLists.txt:113 (openexr_pkg_config_help)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configure PyIlmBase Version: 2.3.0 Lib API: 24.0.2
CMake Warning (dev) at PyIlmBase/CMakeLists.txt:26 (find_package):
  uninitialized variable 'OPENEXR_VERSION'
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python: /usr/local/bin/python3.6 (found version "3.6.9") found components:  Interpreter Development 
-- Found Python2: /usr/local/bin/python2.7 (found version "2.7.16") found components:  Interpreter Development 
-- Found Python3: /usr/local/bin/python3.6 (found version "3.6.9") found components:  Interpreter Development 
: Found Python 2.7.16 and 3.6.9
-- Found Python2 libraries: 27
-- Found Python3 libraries: 36
-- Found Boost: /usr/local/include (found version "1.70.0") found components:  python27 python36 missing components:  python python2 python3
Found Python 2 boost: Boost::python27
Found Python 3 boost: Boost::python36
CMake Warning at PyIlmBase/config/NumPyLocate.cmake:40 (message):
  Found numpy version in python 2.7.16, but unable to locate header files
Call Stack (most recent call first):
  PyIlmBase/CMakeLists.txt:133 (include)


-- Found NumPy 1.16.4 for Python 3.6.9: /usr/local/lib/python3.6/site-packages/numpy/core/include
CMake Warning (dev) at PyIlmBase/config/ModuleDefine.cmake:20 (set_target_properties):
  uninitialized variable 'PYILMBASE_OUTPUT_OUTROOT'
Call Stack (most recent call first):
  PyIlmBase/config/ModuleDefine.cmake:102 (pyilmbase_add_library_priv)
  PyIlmBase/PyIex/CMakeLists.txt:4 (pyilmbase_define_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at PyIlmBase/config/ModuleDefine.cmake:20 (set_target_properties):
  uninitialized variable 'PYILMBASE_OUTPUT_OUTROOT'
Call Stack (most recent call first):
  PyIlmBase/config/ModuleDefine.cmake:129 (pyilmbase_add_library_priv)
  PyIlmBase/PyIex/CMakeLists.txt:4 (pyilmbase_define_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at PyIlmBase/config/ModuleDefine.cmake:20 (set_target_properties):
  uninitialized variable 'PYILMBASE_OUTPUT_OUTROOT'
Call Stack (most recent call first):
  PyIlmBase/config/ModuleDefine.cmake:102 (pyilmbase_add_library_priv)
  PyIlmBase/PyImath/CMakeLists.txt:4 (pyilmbase_define_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at PyIlmBase/config/ModuleDefine.cmake:20 (set_target_properties):
  uninitialized variable 'PYILMBASE_OUTPUT_OUTROOT'
Call Stack (most recent call first):
  PyIlmBase/config/ModuleDefine.cmake:129 (pyilmbase_add_library_priv)
  PyIlmBase/PyImath/CMakeLists.txt:4 (pyilmbase_define_module)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configure OpenEXR Viewers Version: 2.3.0 Lib API: 24.0.1
-- Found OpenGL: /usr/local/lib/libGL.so   
-- Found X11: /usr/local/include   
-- Looking for XOpenDisplay in /usr/local/lib/libX11.so;/usr/local/lib/libXext.so
-- Looking for XOpenDisplay in /usr/local/lib/libX11.so;/usr/local/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found FLTK: /usr/local/lib/libfltk_images.so;/usr/local/lib/libfltk_forms.so;/usr/local/lib/libfltk_gl.so;/usr/local/lib/libGL.so;/usr/local/lib/libfltk.so  
-- Found GLUT: /usr/local/lib/libglut.so  
CMake Warning at OpenEXR_Viewers/config/LocateCg.cmake:37 (message):
  Unable to locate Cg header
Call Stack (most recent call first):
  OpenEXR_Viewers/CMakeLists.txt:47 (include)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/mandree/VCS-other/openexr.git/_build
```

**Comment by mandree** [comment]
Hmm... Boost 1.71 on FreeBSD 12 amd64 and ninja test fails:

```
The following tests FAILED:
	  8 - PyIlmBase.PyImathTest_Python2 (SEGFAULT)
	  9 - PyIlmBase.PyImathTest_Python3 (SEGFAULT)
	 10 - PyIlmBase.PyImathNumpyTest_Python2 (Failed)
	 11 - PyIlmBase.PyImathNumpyTest_Python3 (SEGFAULT)
```

I haven't tested with older Boost 1.70 yet or made any attempts of figuring out what's going on.

**Comment by kdt3rd** [comment]
first steps first, at least it's compiling :)

We are seeing other failures in PyImath on other platforms as well, so your issue may not be isolated to freebsd, but rather tests that are testing against values only one combination of c / math libraries / compilers produce.

**Comment by mandree** [comment]
Regarding the unedited prior question, even after installing numpy properly, I had to add CXXFLAGS=-I/usr/local/include to the cmake environment else I'd see `fatal error: 'boost/python.hpp' file not found`

**Comment by kdt3rd** [comment]
I edited the question because I saw that you were running with those CXXFLAGS still and answered my own question :)

I finally got a VM of freeBSD installed (12.0). I forgot to test the fixes I've done to correctly error when numpy is not installed before I installed numpy, but with all the PRs I have submitted, I was able to do `cmake -G Ninja ..` and have the build go through cleanly for both python2 and python3 (i.e. without having to specify CXXFLAGS). The tests even run and pass :)

I ignored the viewers entirely, they are antiquated, and not necessary if you have OpenImageIO or any other viewer that supports exr.

Anyway, check back in a couple days, once others review my changes and we get it all merged in, freebsd should be good to go without any special fiddling (finally).

**Comment by mandree** [comment]
Kimball, fine for me. Drop me a note when it's been all merged and pushed and I'll retry. Thank you!

**Comment by kdt3rd** [comment]
OK, everything should be all merged in. I was able to compile the tests and have them all run for python2 & 3, and the normal libraries with just a `cmake -G Ninja ..` as the cmake setup step. Hopefully you will find the same

**Comment by mandree** [comment]
Looking mostly fine here, but "ninja test" sees one failure if Numpy is missing - I think it should skip the test in that case:
```
...
      Start 10: PyIlmBase.PyImathNumpyTest_Python2
10/11 Test #10: PyIlmBase.PyImathNumpyTest_Python2 ...***Failed    0.02 sec
      Start 11: PyIlmBase.PyImathNumpyTest_Python3
11/11 Test #11: PyIlmBase.PyImathNumpyTest_Python3 ...   Passed    0.29 sec
```

**Comment by mandree** [comment]
With py27-numpy also installed, all tests pass on FreeBSD 12.0 amd64.

**Comment by cary-ilm** [comment]
Thanks. Closing the issue for now, feel free to re-open or file a new issue if you need further help.
