### ISSUE TITLE
Build on Ubuntu 22.04 fails with automatically provided Imath

### ISSUE THREAD

**Issue by chrismile** [AcademySoftwareFoundation/openexr#2035]
Building OpenEXR on Ubuntu 22.04 with the automatically provided version of Imath fails on Ubuntu 22.04. This has also been reported at https://github.com/chrismile/CloudRendering/issues/8 by @mzccccccc. I have replicated the same issue on my end. On Ubuntu 24.04, I don't face the issue, as the version of Imath in the package sources is used instead automatically during the build.

How to reproduce the OpenEXR compilation errors:
```
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release  -DOPENEXR_INSTALL=ON -DOPENEXR_INSTALL_TOOLS=OFF
make -j $(nproc)
```

Output:

```
cmake .. -DCMAKE_BUILD_TYPE=Release  -DOPENEXR_INSTALL=ON -DOPENEXR_INSTALL_TOOLS=OFF
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building against C++ Standard: 17
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libdeflate'
--   Found libdeflate, version 1.10
-- Using libdeflate from /usr/lib/x86_64-linux-gnu/libdeflate.so
CMake Warning at cmake/OpenEXRSetup.cmake:320 (find_package):
  By not providing "FindImath.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Imath", but
  CMake did not find one.

  Could not find a package configuration file provided by "Imath" (requested
  version 3.1) with any of the following names:

    ImathConfig.cmake
    imath-config.cmake

  Add the installation prefix of "Imath" to CMAKE_PREFIX_PATH or set
  "Imath_DIR" to a directory containing one of the above files.  If "Imath"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)


-- Imath was not found, installing from https://github.com/AcademySoftwareFoundation/Imath.git (main)
-- Imath is configuring as a cmake sub project
-- Configure Imath 3.2.0-dev, library API version: 30.3.2.0
-- Imath pkg-config generation enabled
-- Looking for sin in m
-- Looking for sin in m - found
-- Imath interface dirs $<BUILD_INTERFACE:/home/neuhauser/Programming/Test/openexr/build/_deps/imath-src/src/Imath>;$<BUILD_INTERFACE:/home/neuhauser/Programming/Test/openexr/build/_deps/imath-build/config>;$<INSTALL_INTERFACE:include>;$<INSTALL_INTERFACE:include/Imath>
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN - Success
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX - Success
-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - found
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT - Success
-- Looking for include file semaphore.h
-- Looking for include file semaphore.h - found
-- OpenEXR pkg-config generation enabled
-- Configure OpenEXR 3.4.0-dev, library API version: 99.3.4.0
-- Building OpenEXR libraries
-- Building OpenEXR tools
-- Building OpenEXR examples
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- adding bin tests
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/TestImages/GrayRampsHorizontal.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/LuminanceChroma/Garden.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/ColorCodedLevels.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/WavyLinesLatLong.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/WavyLinesCube.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/LuminanceChroma/Flowers.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiView/Adjuster.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/Rec709_YC.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/Rec709.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/XYZ_YC.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/XYZ.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/TestImages/GammaChart.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Beachball/singlepart.0001.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/v2/LeftView/Balls.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/v2/Stereo/Trunks.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Beachball/multipart.0001.exr
-- clang-format not found.
-- Configuring done
CMake Error at build/_deps/imath-src/src/Imath/CMakeLists.txt:59 (add_library):
  Cannot find source file:

    /home/neuhauser/Programming/Test/openexr/build/config/ImathConfig.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at build/_deps/imath-src/src/Imath/CMakeLists.txt:59 (add_library):
  No SOURCES given to target: Imath


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Using the fix using `FetchContent_Populate` described in https://github.com/AcademySoftwareFoundation/openexr/issues/1888 unfortunately does not resolve the issue. In this case, I get this output for the build commands:

```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building against C++ Standard: 17
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libdeflate'
--   Found libdeflate, version 1.10
-- Using libdeflate from /usr/lib/x86_64-linux-gnu/libdeflate.so
CMake Warning at cmake/OpenEXRSetup.cmake:320 (find_package):
  By not providing "FindImath.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Imath", but
  CMake did not find one.

  Could not find a package configuration file provided by "Imath" (requested
  version 3.1) with any of the following names:

    ImathConfig.cmake
    imath-config.cmake

  Add the installation prefix of "Imath" to CMAKE_PREFIX_PATH or set
  "Imath_DIR" to a directory containing one of the above files.  If "Imath"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)


-- Imath was not found, installing from https://github.com/AcademySoftwareFoundation/Imath.git (main)
CMake Error at cmake/OpenEXRSetup.cmake:351 (get_target_property):
  get_target_property() called with non-existent target "Imath".
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)


CMake Error at cmake/OpenEXRSetup.cmake:352 (get_target_property):
  get_target_property() called with non-existent target "ImathConfig".
Call Stack (most recent call first):
  CMakeLists.txt:66 (include)


-- Imath interface dirs 
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN
-- Performing Test OPENEXR_IMF_HAVE_SYSCONF_NPROCESSORS_ONLN - Success
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX
-- Performing Test OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX - Success
-- Looking for include file ucontext.h
-- Looking for include file ucontext.h - found
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT
-- Performing Test IEX_HAVE_CONTROL_REGISTER_SUPPORT - Success
-- Looking for include file semaphore.h
-- Looking for include file semaphore.h - found
-- OpenEXR pkg-config generation enabled
-- Configure OpenEXR 3.4.0-dev, library API version: 99.3.4.0
-- Building OpenEXR libraries
-- Building OpenEXR tools
-- Building OpenEXR examples
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- adding bin tests
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/TestImages/GrayRampsHorizontal.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/LuminanceChroma/Garden.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/ColorCodedLevels.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/WavyLinesLatLong.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiResolution/WavyLinesCube.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/LuminanceChroma/Flowers.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/MultiView/Adjuster.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/Rec709_YC.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/Rec709.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/XYZ_YC.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Chromaticities/XYZ.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/TestImages/GammaChart.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Beachball/singlepart.0001.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/v2/LeftView/Balls.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/v2/Stereo/Trunks.exr
-- Downloading https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/v1.0/Beachball/multipart.0001.exr
-- clang-format not found.
-- Configuring incomplete, errors occurred!
See also "/home/neuhauser/Programming/Test/CloudRendering/third_party/openexr-src/build/CMakeFiles/CMakeOutput.log".
```

**Comment by cary-ilm** [comment]
I'm seeing this, too, I think the lasted update to Imath broke something. I'm investigating.

**Comment by Mallchad** [comment]
Did you see some progress on your end because it's suddenly building for me again with no changes. @cary-ilm 
(this is semi-rhetorical I checked)

**Comment by cary-ilm** [comment]
Yes, sorry, it did indeed turn out to be a problem introduced on the main branch of Imath, which your build is pulling from. I fixed it yesterday, which appears to have resolved your problem. Thanks for the report. I'm looking into adding a test to validate this doesn't break again, but it's a little more complicated than I thought. 

Closing, but if have any further issues, feel free to reopen.
