### ISSUE TITLE
Broken version header files?

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openexr#1397]
Possibly caused by #1386, OSL's "bleeding edge" CI test that uses top-of-main OpenEXR is getting this suspicious build break:

```
In file included from /home/runner/ext/dist/include/OpenEXR/ImfExport.h:9,
                 from /home/runner/ext/dist/include/OpenEXR/ImfForward.h:15,
                 from /home/runner/ext/dist/include/OpenEXR/ImfChannelList.h:16,
                 from /home/runner/work/OpenShadingLanguage/OpenShadingLanguage/src/liboslexec/shadingsys.cpp:34:
/home/runner/ext/dist/include/OpenEXR/OpenEXRConfig.h:11:10: fatal error: openexr_version.h: No such file or directory
   11 | #include <openexr_version.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by meshula** [comment]
Ah, I *did* need that installation line that we removed in code review. When I push a fix, will the "bleeding edge" CI test run, so I can monitor an outcome there?

**Comment by lgritz** [comment]
I can force it to run by poking the button to rerun one of the failed tests.

**Comment by meshula** [comment]
I think this fixes it https://github.com/AcademySoftwareFoundation/openexr/pull/1398

please LMK how that goes

**Comment by meshula** [comment]
@Vertexwahn This change impacts bazel/example. Sadly the break doesn't follow any of the ones you've helped me fix previously. I'm not sure why the example can't see the openexr dependencies. I'm guessing maybe

```
deps = ["//:OpenEXR", "//:OpenEXRCore"],
```

but I don't really understand why that's necessary, since it's not also specifying Imath and other dependencies.

**Comment by lgritz** [comment]
Fixed OSL's CI

**Comment by meshula** [comment]
Great, thanks for the confirmation. Enabling OpenEXRConfig.h to be able to include a file from OpenEXR needs another look; maybe the version should be parsed from the config.in instead to avoid all the CI, build system, and packaging jujitsu that goes along with a parameterized configuration file.

**Comment by Vertexwahn** [comment]
@meshula 

Bazel assumes includes are relative to the **WORKSPACE.bazel** file. When trying to build Iex (`bazel build //:Iex`) you are including "OpenEXRCore/openexr_version.h" - but the expected path would be "src/lib/OpenEXRCore/openexr_version.h" (relative to the _WORKSPACE_ file). Via the `includes` attribute of `cc_library` additional include dirs can be set. You need to add here "src/lib".

Here is the diff to fix the issues:

```diff
diff --git a/BUILD.bazel b/BUILD.bazel
index 0e932677..17140b27 100644
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -105,6 +105,7 @@ cc_library(
         "//conditions:default": [],
     }),
     includes = [
+        "src/lib",
         "src/lib/Iex",
         "src/lib/OpenEXR",
         "src/lib/OpenEXRCore",
@@ -231,6 +232,7 @@ cc_library(
         "//conditions:default": [],
     }),
     includes = [
+        "src/lib",
         "src/lib/IlmThread",
         "src/lib/OpenEXR",
         "src/lib/OpenEXRCore",
```

Branch with this changes included is here: https://github.com/Vertexwahn/openexr/tree/fix-it

Imath is a transitive dependency of OpenEXR. To see the full dependency graph you can do:

```
bazel query --noimplicit_deps 'deps(//bazel/example:Demo)' --output graph > graph.in
dot -Tpng < graph.in > dependency_graph.png
```

![local_execution_deps](https://user-images.githubusercontent.com/3775001/235324707-924ae76f-7605-4157-a398-81ad42e229e0.png)

**Comment by cary-ilm** [comment]
Culling old issues. I believe this has been resolved.
