### ISSUE TITLE
FTBFS with glibc 2.43

### ISSUE THREAD

**Issue by antonio-rojas** [AcademySoftwareFoundation/openexr#2254]
OpenEXR 3.4.4 and 3.4.5 fail to build on Linux x86_64 with glibc 2.43:
```
In file included from /build/openexr/src/openexr/src/lib/OpenEXRCore/internal_dwa_table_init.c:9:
/build/openexr/src/openexr/src/lib/OpenEXRCore/internal_thread.h:32:17: warning: ‘ONCE_FLAG_INIT’ redefined
   32 | #        define ONCE_FLAG_INIT PTHREAD_ONCE_INIT
      |                 ^~~~~~~~~~~~~~
In file included from /usr/include/stdlib.h:1191,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/mm_malloc.h:27,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/xmmintrin.h:34,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/immintrin.h:31,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include/x86intrin.h:32,
                 from /usr/include/Imath/half.h:185,
                 from /build/openexr/src/openexr/src/lib/OpenEXRCore/internal_coding.h:24,
                 from /build/openexr/src/openexr/src/lib/OpenEXRCore/internal_dwa_table_init.c:8:
/usr/include/bits/types/once_flag.h:25:9: note: this is the location of the previous definition
   25 | #define ONCE_FLAG_INIT __ONCE_FLAG_INIT
      |         ^~~~~~~~~~~~~~
/build/openexr/src/openexr/src/lib/OpenEXRCore/internal_thread.h:33:24: error: conflicting types for ‘once_flag’; have ‘pthread_once_t’ {aka ‘int’}
   33 | typedef pthread_once_t once_flag;
      |                        ^~~~~~~~~
/usr/include/bits/types/once_flag.h:24:21: note: previous declaration of ‘once_flag’ with type ‘once_flag’
   24 | typedef __once_flag once_flag;
      |                     ^~~~~~~~~
/build/openexr/src/openexr/src/lib/OpenEXRCore/internal_thread.h:35:1: error: conflicting types for ‘call_once’; have ‘void(int *, void (*)(void))’
   35 | call_once (once_flag* flag, void (*func) (void))
      | ^~~~~~~~~
/usr/include/stdlib.h:1195:13: note: previous declaration of ‘call_once’ with type ‘void(once_flag *, void (*)(void))’
 1195 | extern void call_once (once_flag *__flag, void (*__func)(void));
      |             ^~~~~~~~~
```

**Comment by cary-ilm** [comment]
See #2262 for a fix awaiting approval.  

The v3.4.6 release went out with an incorrect announcement that it fixed this, but the fix isn't actually in yet, a glitch in the notes process.

**Comment by cary-ilm** [comment]
resolved in v3.4.7
