### ISSUE TITLE
Cannot build against openexr 3.4.2 (imath 3.2.2)

### ISSUE THREAD

**Issue by HappySeaFox** [AcademySoftwareFoundation/openexr#2158]
Steps to reproduce:

1. Install openexr through `vcpkg` on Windows 11 and MSVC 2022:
```
vcpkg install openexr
...

vcpkg list openexr
openexr:x64-windows          3.4.2               OpenEXR is a high dynamic-range (HDR) image file...

vcpkg list imath
imath:x64-windows              3.2.2               Imath is a C++ and Python library of 2D and 3D v...
```

2. Compile a test program with C++17 enabled. You can use https://github.com/HappySeaFox/sail or https://github.com/HappySeaFox/sail/tree/master/src/sail-codecs/openexr
3. Observe compilations errors:

```bash
  Generating Code...
C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(911,53): error C2059: syntax error: ')' [C:\projects\sail\build\src\sail-codecs\openexr\sail-c
odec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(911,53): error C2334: unexpected token(s) preceding ':'; skipping apparent function body [C:\p
rojects\sail\build\src\sail-codecs\openexr\sail-codec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(974,1): error C2143: syntax error: missing ')' before ';' [C:\projects\sail\build\src\sail-cod
ecs\openexr\sail-codec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(974,1): error C2059: syntax error: ')' [C:\projects\sail\build\src\sail-codecs\openexr\sail-co
dec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(974,1): error C2238: unexpected token(s) preceding ';' [C:\projects\sail\build\src\sail-codecs
\openexr\sail-codec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\half.h(982,14): error C2628: 'std::numeric_limits<Imath_3_2::half>' followed by 'void' is illegal (di
d you forget a ';'?) [C:\projects\sail\build\src\sail-codecs\openexr\sail-codec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')

C:\projects\vcpkg\installed\x64-windows\include\Imath\ImathVec.h(125,27): error C2947: expecting '>' to terminate template-parameter-list, found '<' [C:\pr
ojects\sail\build\src\sail-codecs\openexr\sail-codec-openexr.vcxproj]
  (compiling source file '../../../../src/sail-codecs/openexr/helpers.cpp')
```

Problematic code is in `half.h`:

```cpp
template <> class numeric_limits<IMATH_INTERNAL_NAMESPACE::half>
{
public:
    static const bool is_specialized = true;

    static constexpr IMATH_INTERNAL_NAMESPACE::half min () IMATH_NOEXCEPT       <=========
    {
        return IMATH_INTERNAL_NAMESPACE::half (IMATH_INTERNAL_NAMESPACE::half::FromBits, 0x0400); /*HALF_MIN*/
    }
```

I also compile in Ubuntu 24.04 with OpenEXR 3.1.5-5.1build3, it works fine. It seems the problem is with 3.4.2 on Windows.

**Comment by HappySeaFox** [comment]
It seems that defining `NOMINMAX` and **not** declaring `using namespace OPENEXR_IMF_INTERNAL_NAMESPACE;` (i.e. using fully qualified names) resolves the issue!
